default:
  image: node:latest

.default_before_script: &default_before_script
  before_script:
    - yarn install --frozen-lockfile --cache-folder .yarn
    - yarn add moment@2.29.1
    - echo '//gitlab.com/api/v4/projects/${CI_PROJECT_ID}/packages/npm/:_authToken=${CI_JOB_TOKEN}' | tee --append .npmrc
  cache:
    paths:
      - node_modules/
      - .yarn

workflow:
  rules:
    - if: $CI_COMMIT_BRANCH

stages:
  - test
  - build
  - release

variables:
  GITLAB_NPM_TOKEN: $CI_JOB_TOKEN
  GITLAB_NPM_CONFIG_REGISTRY: https://gitlab.com/api/v4/projects/${CI_PROJECT_ID}/packages/npm/
  PUBLIC_NPM_TOKEN: $NPM_TOKEN
  PUBLIC_NPM_CONFIG_REGISTRY: https://registry.npmjs.org/

include:
  - template: Dependency-Scanning.gitlab-ci.yml
  - template: SAST.gitlab-ci.yml

eslint:
  <<: *default_before_script
  stage: test
  script:
    - yarn lint

jest:
  <<: *default_before_script
  stage: test
  script:
    - yarn test
  artifacts:
    paths:
      - test-report.xml
    reports:
      junit: test-report.xml

build:
  <<: *default_before_script
  stage: build
  needs: []
  script:
    - yarn build
  artifacts:
    paths:
      - build/

publish:
  <<: *default_before_script
  stage: release
  script:
    - yarn semantic-release --debug
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
