default:
  image: node:latest
  before_script:
    - yarn install --frozen-lockfile --cache-folder .yarn
  cache:
    paths:
      - node_modules/
      - .yarn

workflow:
  rules:
    - if: $CI_COMMIT_BRANCH
    - if: $CI_COMMIT_TAG

stages:
  - build

build:
  stage: build
  needs: []
  script:
    - yarn build
  artifacts:
    paths:
      - build/
