import { normalize } from '../src/index';

// Suppress warnings generated by Moment when it
// tries to parse an invalid string value
console.warn = jest.fn();

describe('normalize', () => {
  test.each`
    input            | expected
    ${'2015-11-30'}  | ${'2015-11-30'}
    ${'2015-W49'}    | ${'2015-11-30'}
    ${'2015-W49-WE'} | ${'2015-12-05'}
    ${'2015-11'}     | ${'2015-11-01'}
    ${'2015-11-XX'}  | ${'2015-11-01'}
    ${'2015'}        | ${'2015-01-01'}
    ${'2015-XX-XX'}  | ${'2015-01-01'}
    ${'201X'}        | ${'2010-01-01'}
    ${'2015-WI'}     | ${'2015-12-21'}
    ${'2015-SP'}     | ${'2015-03-21'}
    ${'2015-SU'}     | ${'2015-06-21'}
    ${'2015-FA'}     | ${'2015-09-21'}
  `('returns $expected when $input is provided', ({ input, expected }) => {
    expect(normalize(input).format('YYYY-MM-DD')).toBe(expected);
  });

  test.each`
    input
    ${null}
    ${undefined}
    ${''}
    ${'not a valid date'}
    ${false}
    ${true}
    ${{ an: 'object' }}
    ${new Date()}
    ${function () {}}
    ${/hello/}
    ${new Map()}
  `(
    'returns an invalid Moment object when $input is provided',
    ({ input, expected }) => {
      expect(normalize(input).isValid()).toBe(false);
    },
  );
});
